# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loader.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from finalUI import Ui_MainWindow

counter = 0


class Ui_loader(object):

    def setupUi(self, loader):
        loader.setObjectName("loader")
        loader.resize(681, 400)

        # todo removing window's frame and background
        loader.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        loader.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        # todo setting timer
        self.timer = QtCore.QTimer()
        # todo changing text
        self.timer.singleShot(0, lambda: self.changing_label.setText("creating files..."))
        self.timer.singleShot(2200, lambda: self.changing_label.setText("loading files..."))
        self.timer.singleShot(3700, lambda: self.changing_label.setText("establishing connections..."))
        self.timer.singleShot(4400, lambda: self.changing_label.setText("loading user interface..."))

        self.centralwidget = QtWidgets.QWidget(loader)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.L_frame = QtWidgets.QFrame(self.centralwidget)
        self.L_frame.setStyleSheet("background-image: url(:/newPrefix/images/diamondbg.jpg);\n"
                                   "background-position: center;\n"
                                   "background-repeat: no-repeat;\n"
                                   "background-attachment: fixed;\n"
                                   "border-radius:10px;")
        self.L_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.L_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.L_frame.setObjectName("L_frame")
        self.frame = QtWidgets.QFrame(self.L_frame)
        self.frame.setGeometry(QtCore.QRect(-1, 100, 661, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #333333;")
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #4161AD;")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.L_frame)
        self.label.setGeometry(QtCore.QRect(0, 160, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#0683C2;\n"
                                 "background:none;\n"
                                 "")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.L_frame)
        self.progressBar.setGeometry(QtCore.QRect(40, 280, 581, 20))
        self.progressBar.setStyleSheet("QProgressBar{\n"
                                       "background:none;\n"
                                       "  background-color: #cde1e8;\n"
                                       "border-style:none;\n"
                                       "border-radius:10px;\n"
                                       "text-align:center;\n"
                                       "color:rgb(38, 38, 38);\n"
                                       "}\n"
                                       "QProgressBar::chunk{\n"
                                       "border-radius:10px;\n"
                                       "    \n"
                                       "    background-color: qlineargradient(spread:pad, x1:0, y1:0.54, x2:1, y2:0.556818, stop:0 rgba(0, 168, 155, 255), stop:0.284091 rgba(6, 131, 194, 255), stop:0.619318 rgba(6, 131, 194, 255), stop:0.977273 rgba(145, 65, 152, 255));\n"
                                       "}")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.label_4 = QtWidgets.QLabel(self.L_frame)
        self.label_4.setGeometry(QtCore.QRect(330, 340, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(65, 97, 173);\n"
                                   "background:none;\n"
                                   "")
        self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.L_frame)
        self.label_5.setGeometry(QtCore.QRect(0, 40, 661, 71))
        self.label_5.setStyleSheet("background:none;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/newPrefix/images/logo50.png"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.changing_label = QtWidgets.QLabel(self.L_frame)
        self.changing_label.setGeometry(QtCore.QRect(0, 310, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.changing_label.setFont(font)
        self.changing_label.setStyleSheet("color: rgb(65, 97, 173);\n"
                                          "background:none;")
        self.changing_label.setAlignment(QtCore.Qt.AlignCenter)
        self.changing_label.setObjectName("changing_label")
        self.label_7 = QtWidgets.QLabel(self.L_frame)
        self.label_7.setGeometry(QtCore.QRect(20, 340, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(65, 97, 173);\n"
                                   "background:none;")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.L_frame)
        self.label_8.setGeometry(QtCore.QRect(0, 240, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(65, 97, 173);\n"
                                   "background:none;\n"
                                   "")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.L_frame, 0, 0, 1, 1)
        loader.setCentralWidget(self.centralwidget)

        self.retranslateUi(loader)
        QtCore.QMetaObject.connectSlotsByName(loader)

    def retranslateUi(self, loader):
        _translate = QtCore.QCoreApplication.translate
        loader.setWindowTitle(_translate("loader", "MainWindow"))
        self.label_2.setText(_translate("loader", "People"))
        self.label_3.setText(_translate("loader", "Finder"))
        self.label.setText(_translate("loader", "a n y t i m e ,  a n y w h e r e ."))
        self.label_4.setText(_translate("loader", "<strong>Created</strong>: Atif Saleem"))
        self.changing_label.setText(_translate("loader", "loading files..."))
        self.label_7.setText(_translate("loader", "<strong>&copy; 2020</strong> All rights reserved"))
        self.label_8.setText(_translate("loader", "Easiest way to find lost people."))


import nx

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    loader = QtWidgets.QMainWindow()
    ui = Ui_loader()
    ui.setupUi(loader)
    loader.show()
    sys.exit(app.exec_())
